### PR TITLE
move visualization functions for corsika_output to a dedicated visualize file

### PR DESCRIPTION
**Pull request by VictorBarbosaMartins**
Nothing new here, just moving the plotting functions for the `corsika_output` module from the `utils/visualize.py` to a new file `corsika/corsika_output_visualize.py`

Solves #473

### CODE REVIEW

**Review by orelgueta — APPROVED** [review]
Looks good, thanks!

**Comment by VictorBarbosaMartins** [comment]
Hi @orelgueta, thanks. I just realized that the checks (unit and integration tests) are not running here. Do you have an idea why?

**Comment by orelgueta** [comment]
Yes, #481 should fix it. Perhaps merge #481 and then merge the main to this branch so it triggers running the tests again to see that it works.

**Comment by orelgueta** [comment]
I merged the other PR, merge the main to this branch, push and see if the tests are running now.

**Comment by VictorBarbosaMartins** [comment]
> I merged the other PR, merge the main to this branch, push and see if the tests are running now.

thanks. that seems to work

**Pull request merged**
