### PR TITLE
Remove unused parameter corsika_parameters_file in corsika_runner

### LINKED ISSUE #417: Unused parameter in corsika_runner
https://github.com/gammasim/gammasim-tools/blob/8cdb37a97cf9c4fcf37ed0380927c28e4735cb3a/simtools/corsika/corsika_runner.py#L84

This parameter is set in the simulator, but is not actually used anywhere in the CORSIKA runner. It's seems weird to simply remove it. Any ideas @GernotMaier?

### PR DESCRIPTION
**Pull request by GernotMaier**
Carefully checked if `corsika_parameters_file` is used anywhere. It is indeed not used and safely be removed. 

closes #417

### CODE REVIEW

**Comment by VictorBarbosaMartins** [comment]
I am afraid this is the place where we would be able to change the atmosphere file. I will have a closer look tomorrow to confirm it

**Review by VictorBarbosaMartins — APPROVED** [review]
Good. I think now it is not a problem to remove it

**Review by orelgueta — CHANGES_REQUESTED** [review]
docstring should be put back and corrected, will do myself.

**Review by orelgueta — CHANGES_REQUESTED** [review]
No, I think this PR should be the other way around. We need to pass to the `CorsikaConfig` the `corsika_parameters_file` rather than removing it. 

With this PR we essentially are losing functionality and making that parameter useless in `Simulator` and `CorsikaConfig`. It is functionality we never used, but we should keep it. If you want, scrap this entire PR and I will open a new one later.

**Comment by GernotMaier** [comment]
OK - let's close this.  I was trying to fix #417.

Note that this PR removes an unused variable and all tests pasts after removing. So I think something is inconsistent.

**Comment by orelgueta** [comment]
Yes, that's cause there's a default option in case `None` is passed. I will fix it in a separate PR.

**Pull request closed without merging**
