### PR TITLE
Update corsika/sim_telarray version to 240927

### PR DESCRIPTION
**Pull request by GernotMaier**
Uploaded the most recent corsika/simtel tar ball from

https://www.mpi-hd.mpg.de/hfm/CTA/MC/Software/Testing/corsika7.7_simtelarray.tar.gz

to the cloud space with the date ID 20240927. Changed the github CI accordingly.

Note: this CI is manually triggered.

### CODE REVIEW

**Comment by GernotMaier** [comment]
How to test this? I think the only way is to generate the docker image, download it and test if the changes are implemented?

**Review by orelgueta — APPROVED** [review]
I approve but I guess you check the content before merging.

**Comment by GernotMaier** [comment]
@orelgueta - only notice this now: we have to change the 'date ID' for sim_telarray in three places.

Downloaded and checked that the corsika-simtelarray images is the most recent one.

And note to my self, it is:

`docker pull ghcr.io/gammasim/simtools-corsika-sim-telarray-qgs2-prod6-sc-240927:latest`

and not

`podman pull ghcr.io/gammasim/simtools-corsika_sim_telarray:latest`

**Comment by orelgueta** [comment]
Oh, maybe we should have some sort of default for the `ARG` ones. Something for the future, not critical now.

**Comment by GernotMaier** [comment]
Not sure how to implement the default. Remember that we name the packages with the version included. e.g.

- [simtools-corsika-sim-telarray-qgs2-prod6-sc-240913](https://github.com/gammasim/simtools/pkgs/container/simtools-corsika-sim-telarray-qgs2-prod6-sc-240913)

**Comment by orelgueta** [comment]
I don't know either at this point.

**Pull request merged**
