### PR TITLE
Run upload_from_model_repo from within the container

### PR DESCRIPTION
**Pull request by orelgueta**
Added a note to remind the user (me...) to run the script from within the container.

### CODE REVIEW

**Review by GernotMaier — CHANGES_REQUESTED** [review]
Hmm, I don't need to do this within a container and can run the upload script in my conda environment. Are you sure about this?

**Comment by orelgueta** [comment]
When I do it from outside the container (with the conda environment activated), the connection times out. Perhaps there's something I am missing, but I spent a good 20 minutes yesterday trying to figure it out.

Either way, I have done it so many times now that I probably won't forget anymore, so this PR can be skipped if you wish.

**Comment by GernotMaier** [comment]
I see the issue now - you need to have a `.env` which points to the local DB. It should look like:

```
SIMTOOLS_DB_API_PORT=27017 #Port on the MongoDB server
SIMTOOLS_DB_SERVER='localhost'
SIMTOOLS_DB_API_USER='api' # username for MongoDB
SIMTOOLS_DB_API_PW='password' # Password for MongoDB
SIMTOOLS_DB_API_AUTHENTICATION_DATABASE='admin'
SIMTOOLS_DB_SIMULATION_MODEL='CTAO-Simulation-Model-LATEST'
```

I guess this is something we should add to the documentation.

**Comment by orelgueta** [comment]
I actually tried that and it still didn't work. Maybe I did that wrong though. 

Either way, I agree we should figure out what's the easiest way where it always works and add it to the documentation. Running from within the container is easy, but running from outside the full list chain of
- ./purge_local_db.sh
- ./setup_local_db.sh
- ./upload_from_model_repository_to_db.sh CTAO-Simulation-Model-v0-10-0

is probably easier/clearer.

**Review by GernotMaier — APPROVED** [review]

**Pull request merged**
