### PR TITLE
fix zero padding in old production tool

### LINKED ISSUE #646: production tool with `--array_option` likely not simulating events with `--array_only` option
It might that I am missing something but running the production tool with `--array_only` option and running the job locally is not doing anything. I would expect sim_telarray output somewhere:

```
simtools-production --task simulate --productionconfig prod_config_test.yml --submit_command local --primary gamma --array_only --use_plain_output_path --output_path test_sim_telarray/
```

### PR DESCRIPTION
**Pull request by VictorBarbosaMartins**
Closes #646, #645.

Related to [660](https://github.com/gammasim/simtools/issues/660). For some time the old production tool was not working due to mismatches in the names of the files produced by CORSIKA.

It looks like a simple solution but it took me some time. First I wanted to keep the zero padding, but it was not possible to add the zero padding to the .zst file being saved by the corsika runner. There is a mess with directories, env variables and functions with the same name in the config and runner scripts. Instead, I removed the zero padding from the .zst file being read by simtel_runner. Hopefully that does not break anything in the new production tool.

To review (the test that I was doing locally): 
run the shower and then the array simulator. Check log files and more specifically the zst files in the data directories
```
mkdir test_sim_telarray
simtools-production --task simulate --productionconfig prod_config_test.yml --submit_command local --primary gamma --showers_only --output_path test_sim_telarray/
```

```
simtools-production --task simulate --productionconfig prod_config_test.yml --submit_command local --primary gamma --array_only --use_plain_output_path --output_path test_sim_telarray/
```

Edit: This is also closing #645. Now a bunch of files from the random_generator will not be written locally but only a single  file! That is already much better than before.

### CODE REVIEW

**Comment by GernotMaier** [comment]
@VictorBarbosaMartins - I would like to handover this one to Orel. I am simply not familiar with the naming conventions and what is happening here. Is this ok with you?

**Comment by GernotMaier** [comment]
And maybe we discuss early next week what you call a 'mess' up there so that we can fix it.

**Comment by VictorBarbosaMartins** [comment]
Sounds good!

**Comment by orelgueta** [comment]
Hold on, we definitely want to have zero padding. So removing it cannot be the solution. I need to figure out first why you say it cannot be added in the case of CORSIKA simulations. I will come back and comment further later.

**Comment by VictorBarbosaMartins** [comment]
> Hold on, we definitely want to have zero padding. So removing it cannot be the solution. I need to figure out first why you say it cannot be added in the case of CORSIKA simulations. I will come back and comment further later.

I don't see the reason why we would need the padding in the name of the zst file, which is the final product of the simtel_array simulation, but maybe you can explain me? It costed me some hours to try to implement the missing zero padding during the writing of the file, but it is extremely non-trivial. The place in the code where we name it is based on environmental variable, so we can't deal with the string since the string is not there yet. I am happy if you find another solution, but I wouldnt dedicate too much time on that.

**Comment by orelgueta** [comment]
The word "need" is a strong one. Let's say it is desirable to have zero padding because it means that the files are ordered when you list them in the terminal for example. It also means all files have the exact same structure. This requirement for zero padding came from DPPS (in particular Karl and Max). It is an easy requirement to satisfy, so I don't see a reason why not.

Regarding the exact implementation, I will open a separate PR in a few minutes. It is true that the file name is defined right now using env variables, but that's just a choice Raul made at the time. The values are defined by the user and should be available. Let me see if I can do it quickly.

**Comment by orelgueta** [comment]
OK, I realise now why Raul used the env variables. It is to support the simulation of a range of runs on the same machine (or output to the same directory).

I then thought of a way to implementing the zero padding even when using these env variables (copying from Konrad's implementation in the latest run script), but realised it is not really necessary. We do not plan to simulate a range of runs sequentially or using the batch farm in this way. It is functionality we do not really need and can also be implemented in the future without relying on the internal system of CORSIKA to advance the run numbers.

Therefore, I will open a separate simple PR that fixes this specific issue. Then I will open an issue to remove the entire option of simulating a range of runs (or we retire the old production script in general).

**Comment by VictorBarbosaMartins** [comment]
Closed as already addressed in #735 and #736

**Pull request closed without merging**
