### PR TITLE
remove if statement -> return testing all the output files in integra…

### PR DESCRIPTION
**Pull request by VictorBarbosaMartins**
After discussions in #875, I have realized that the tests for the output files of integrations tests were turned off. I turn them on again, but I have to be honest that I do not know about the impact on the choice for the model version. I will see the results of the integration tests here and evaluate the situation.

Usually the name of output files from integration tests are not related to the model parameter version (or at least it shouldnt). If that is the case, I hope that only applications that are really not working will fail the tests

### CODE REVIEW

**Comment by VictorBarbosaMartins** [comment]
> As discussed in person: this if statement is not correct, but should not be removed entirely. We should do the tests for the output files only for the version outline in the config file.

Ok, I am waiting for your corrections to proceed with my tests. Thanks!

**Comment by GernotMaier** [comment]
I've adjust the code now that it runs only for those model_versions given in the config file.

Unfortunately a bit more complicated as expected, but I've tested all options (without command line, with command line model_version as/as not in config file) and it works as expected.

**Comment by VictorBarbosaMartins** [comment]
> I've adjust the code now that it runs only for those model_versions given in the config file.
> 
> Unfortunately a bit more complicated as expected, but I've tested all options (without command line, with command line model_version as/as not in config file) and it works as expected.

Ok, thanks! it looks like it works now. So, I expect only problematic tools to fail the integration tests now.

**Comment by VictorBarbosaMartins** [comment]
> > I've adjust the code now that it runs only for those model_versions given in the config file.
> > Unfortunately a bit more complicated as expected, but I've tested all options (without command line, with command line model_version as/as not in config file) and it works as expected.
> 
> Ok, thanks! it looks like it works now. So, I expect only problematic tools to fail the integration tests now.

Ups, it doesn't seem to be the case

**Pull request merged**
