### PR TITLE
Update version number for corsika/sim_telarray package (20240913)

### PR DESCRIPTION
**Pull request by GernotMaier**
This PR required the following steps:

- download most recent CORSIKA/sim-telarray package from KB's testing website (date 2024/09/13)
- upload the package to sync and share
- define a new github secret for the actions CLOUD_SIMTEL_230913
- update the workflow for building the docker for CORSIKA/sim-telarray

### CODE REVIEW

**Comment by GernotMaier** [comment]
The relevant action for the docker build of the new corsika/simtel_array version is [here](https://github.com/gammasim/simtools/actions/runs/11027285485/job/30625308828?pr=1158)

**Comment by orelgueta** [comment]
Where do you see a package from the 23rd of September? The last one I see on the website is from the 13th of September, which means it wouldn't include the latest change to testeff. I might be looking in the wrong place though.

**Comment by GernotMaier** [comment]
13th! Misread the numbers. I correct it to make sure we are not confused by it in the future.

**Comment by orelgueta** [comment]
No, but then I would wait with this update until Konrad produces a new tarball. The trigger for this change is the updated testeff, all other changes are not really important.

**Comment by GernotMaier** [comment]
Seems the 'patch' command is not part anymore of almalinux, as I get:

```
./build_all: line 1023: patch: command not found
```

I am adding it now and try again.

**Comment by GernotMaier** [comment]
@orelgueta - I suggest a quick review and merge, even if it doesn't solve your testeff problem. The 'patch' issue was new and is solved here.

Successful building: https://github.com/gammasim/simtools/actions/runs/11031927431

**Review by orelgueta — APPROVED** [review]
From my point of view, the changes are fine, but the illuminator tests failed for some unrelated reason. I approve anyway. 

The only issue is that this PR will close #1152, which it shouldn't. So please reopen the issue once you merge.

**Comment by GernotMaier** [comment]
I think we need to fix the illuminator issue first, e.g., in https://github.com/gammasim/simtools/actions/runs/11031923016/job/30639695323?pr=1158

It is looking for  atm_trans_2156_1_3_2_0_0_0.1_0.1.dat , is this related to the removal of the config files?

**Pull request merged**
